version: '2'

services:

    phpfarm:
        image: splitbrain/phpfarm:wheezy
        volumes_from:
            - app:rw
        ports:
            - "8052:8052"
            - "8053:8053"
            - "8054:8054"
            - "8055:8055"
            - "8056:8056"
            - "8070:8070"
        environment:
            - APACHE_UID=502
        depends_on:
            - mysql
        # links:
            # - mailcatcher:mailcatcher

    nginx:
        image: nginx
        volumes:
            - ./testit.conf:/etc/nginx/conf.d/testit.conf
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
        links:
            - phpfarm:phpfarm
            - phpmyadmin:phpmyadmin
            # - mailcatcher:mailcatcher
        # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=myapp
        volumes_from:
            - database:rw
        command: /bin/bash -c "chmod 777 /database/config/entrypoint.sh && cd /database/config/ && ./entrypoint.sh"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_ABSOLUTE_URI=http://phpmyadmin.spaces.dev/
        restart: always
        ports:
            - "8080:80"
        links:
            - mysql:mysql

    hub:
        image: qualiboo/testing-hub
        ports:
            - "4444:4444"
        links:
            - phpfarm
            - nginx

    # mailcatcher:
    #     image: yappabe/mailcatcher
    #     ports:
    #         - 1025:1025
    #         - 1080:1080



    app:
        image: splitbrain/phpfarm:wheezy
        volumes:
            - ./data:/var/www

    database:
        image: nginx
        volumes:
            - ./database/data:/var/lib/mysql:rw
            - ./database/config/entrypoint.sh:/database/config/entrypoint.sh:rw
