version: '2'
services:
    phpfarm:
        image: splitbrain/phpfarm:wheezy
        volumes:
            - ./data:/var/www:rw
        ports:
            - "8052:8052"
            - "8053:8053"
            - "8054:8054"
            - "8055:8055"
            - "8056:8056"
            - "8070:8070"
        environment:
            - APACHE_UID=502
    nginx:
        image: nginx
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
        links:
            - phpfarm:phpfarm
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
